"""
This module defines functions for saving pipeline history artifacts, like
LLM generation history or images generated by T2I.
"""

import os
from typing import BinaryIO, Iterable, Sequence, TextIO

from PIL import Image


def _write_iterable_to_stream(
    output_stream: TextIO, lines: Iterable[str]
) -> None:
    """Writes contents of an iterable to a text stream, one item per line."""
    output_stream.write("\n".join(lines))


def save_llm_history(
    history: Iterable[str], save_directory: str, filename: str
) -> None:
    """Saves the llm history to a file."""
    os.makedirs(save_directory, exist_ok=True)
    save_path = os.path.join(save_directory, filename)

    with open(save_path, "w") as save_file:
        _write_iterable_to_stream(save_file, history)


def _write_image_to_stream(output_stream: BinaryIO, image: Image.Image) -> None:
    """Writes an image to a stream."""
    image.save(output_stream, format="jpeg")


def save_images_from_iteration(
    images: Sequence[Image.Image],
    save_directory: str,
    iter_number: int,
    concept: str,
) -> None:
    """Saves images from a single pipeline iteration."""
    save_path = os.path.join(
        save_directory, f"iteration_{iter_number}_{concept.replace(" ", "_")}"
    )
    os.makedirs(save_path, exist_ok=True)
    for image_number, image in enumerate(images, 1):
        filename = f"image_{image_number}.jpeg"
        with open(os.path.join(save_path, filename), "wb") as save_file:
            _write_image_to_stream(save_file, image)
